version: "2"
services:
    server:
        build: .
        command:
            /ucx/src/tools/perf/ucx_perftest -c 0 -p 8000
        image: ucx:latest
    client:
        build: .
        depends_on:
            - "server"
        command:
            /ucx/src/tools/perf/ucx_perftest server -p 8000 -t tag_lat -c 0
        image:
            ucx:latest
